services:
  labels-api:
    build: .
    env_file: .env
    networks: [proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.labels.rule=Host(`usage.90ten.life`)"
      - "traefik.http.routers.labels.entrypoints=websecure"
      - "traefik.http.routers.labels.tls.certresolver=letsencrypt"
      - "traefik.http.services.labels.loadbalancer.server.port=8000"
    restart: unless-stopped
networks:
  proxy:
    external: true
